[package]
name = "chicken-coop"
version = "0.1.0"
edition = "2021"
license = "Apache-2"

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
gloo-utils = "0.1"
log = "0.4"
patternfly-yew = { version = "0.4", features = ["icons-fab", "tree"] }
strum = "0.24"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = { version = "0.20", features = ["csr"] }
yew-nested-router = "0.2"